require 'slack-bot-server/commands/help'
require 'slack-bot-server/commands/whoami'
require 'slack-bot-server/commands/ping'
require 'slack-bot-server/commands/headlines'
require 'slack-bot-server/commands/weather'
require 'slack-bot-server/commands/link'
require 'slack-bot-server/commands/history'